words = [
    "astro",
    "astrocommunity",
    "astrocore",
    "astrodark",
    "astrolsp",
    "astrotheme",
    "astroui",
    "augroup",
    "autocmd",
    "autocmds",
    "autocommands",
    "autopairs",
    "basedpyright",
    "breakpoint",
    "bufnr",
    "buftype",
    "catppuccin",
    "cmake",
    "cmdline",
    "colorschemes",
    "commentstring",
    "copen",
    "dadbod",
    "dapui",
    "djangohtml",
    "djlsp",
    "esc",
    "exrc",
    "foorc",
    "fooscript",
    "gitcommit",
    "heirline",
    "highlighturl",
    "htmldjango",
    "keymaps",
    "lefthand",
    "loclist",
    "lopen",
    "lspconfig",
    "mapleader",
    "maplocalleader",
    "matchparen",
    "mkdp",
    "neotest",
    "neovim",
    "nofile",
    "nohlsearch",
    "noice",
    "noremap",
    "nvim",
    "nvim's",
    "pipfile",
    "pyrefly",
    "relativenumber",
    "sessionizer",
    "severities",
    "signcolumn",
    "stopline",
    "tabline",
    "templ",
    "tmux",
    "undotree",
    "venv",
    "vimdoc",
    "vimdocs",
    "vscode",
    "xdg",
]
