gui:
  theme:
    optionsTextColor:
      - "#89b4fa"
    markedBaseCommitFgColor:
      - "#181825"
    markedBaseCommitBgColor:
      - "#f38ba8"
    inactiveBorderColor:
      - "#89b4fa"
    defaultFgColor:
      - "#cdd6f4"
    cherryPickedCommitFgColor:
      - "#f5c2e7"
    unstagedChangesColor:
      - "#f38ba8"
    cherryPickedCommitBgColor:
      - "#45475a"
    activeBorderColor:
      - "#fab387"
      - "bold"
    selectedLineBgColor:
      - "#45475a"
    searchingActiveBorderColor:
      - "#fab387"
      - "bold"
