return {
  -- "folke/noice.nvim",
  -- -- opts = {
  -- --
  -- --   views = {
  -- --     notify = { merge = false, replace = false },
  -- --   },
  -- -- },
  -- keys = {
  --   -- Clear search + dismiss Noice
  --   {
  --     "<Esc>",
  --     function()
  --       -- run your actions
  --       vim.cmd "nohlsearch"
  --       vim.cmd "NoiceDismiss"
  --       -- return <Esc> so Flash sees it
  --       return "<Esc>"
  --     end,
  --     mode = "n",
  --     expr = true, -- THIS is required so the return value is sent as keys
  --     silent = true,
  --     desc = "Clear search + dismiss Noice",
  --   },
  --   {
  --     "<Leader>N",
  --     "<nop>",
  --     mode = "n",
  --     silent = true,
  --     desc = " Noice",
  --   },
  --   -- Noice last message
  --   {
  --     "<Leader>Nl",
  --     function() require("noice").cmd "last" end,
  --     mode = "n",
  --     desc = "Noice Last Message",
  --   },
  --   -- Noice message history
  --   {
  --     "<Leader>Nh",
  --     function() require("noice").cmd "history" end,
  --     mode = "n",
  --     desc = "Noice History",
  --   },
  --   -- Noice message dismiss
  --   {
  --     "<Leader>Nd",
  --     function() require("noice").cmd "dismiss" end,
  --     mode = "n",
  --     desc = "Noice Dismiss",
  --   },
  --   -- Noice message errors
  --   {
  --     "<Leader>Ne",
  --     function() require("noice").cmd "errors" end,
  --     mode = "n",
  --     desc = "Noice Errors",
  --   },
  --   -- Noice disable
  --   {
  --     "<Leader>ND",
  --     function() require("noice").cmd "disable" end,
  --     mode = "n",
  --     desc = "Noice Disable",
  --   },
  --   -- Noice enable
  --   {
  --     "<Leader>NE",
  --     function() require("noice").cmd "enable" end,
  --     mode = "n",
  --     desc = "Noice Enable",
  --   },
  --   -- Noice stats
  --   {
  --     "<Leader>Ns",
  --     function() require("noice").cmd "stats" end,
  --     mode = "n",
  --     desc = "Noice Stats",
  --   },
  --   -- Noice messages
  --   {
  --     "<Leader>Nm",
  --     function() require("noice").cmd "messages" end,
  --     mode = "n",
  --     desc = "Noice Messages",
  --   },
  --   -- Noice stats
  --   {
  --     "<Leader>Np",
  --     function() require("noice").cmd "pick" end,
  --     mode = "n",
  --     desc = "Noice Picker",
  --   },
  --
  --   -- Redirect commandline with Shift-Enter
  --   {
  --     "<S-Enter>",
  --     function() require("noice").redirect(vim.fn.getcmdline()) end,
  --     mode = "c",
  --     desc = "Redirect Cmdline",
  --   },
  --   -- Noice LSP scrolling (<C-f>)
  --   {
  --     "<C-f>",
  --     function()
  --       if not require("noice.lsp").scroll(4) then return "<C-f>" end
  --     end,
  --     mode = { "n", "i", "s" },
  --     expr = true,
  --     silent = true,
  --     desc = "Noice LSP scroll (down)",
  --   },
  --   -- Noice LSP scrolling (<C-b>)
  --   {
  --     "<C-b>",
  --     function()
  --       if not require("noice.lsp").scroll(-4) then return "<C-b>" end
  --     end,
  --     mode = { "n", "i", "s" },
  --     expr = true,
  --     silent = true,
  --     desc = "Noice LSP scroll (up)",
  --   },
  -- },
}
