return {
  -- {
  --   "jmbuhr/otter.nvim",
  --
  --   -- Lazy load when needed
  --   ft = { "html" },
  --
  --   keys = {
  --     {
  --       "<Leader>Oa",
  --       function() require("otter").activate() end,
  --       desc = "Otter: Activate Javascript",
  --     },
  --     {
  --       "<Leader>Ol",
  --       "<cmd>ls!<cr>",
  --       desc = "Otter: List buffers",
  --     },
  --     {
  --       "<Leader>Oi",
  --       "<cmd>LspInfo<cr>",
  --       desc = "Otter: LSP info",
  --     },
  --   },
  --
  --   dependencies = {
  --     "nvim-treesitter/nvim-treesitter",
  --   },
  -- },
}
